### PR TITLE
Export notes as txt

### LINKED ISSUE #2: Export Note As TXT
Add option to export note content as txt file

### PR DESCRIPTION
**Pull request by ryanyychen**
Closes #2, #15 
Had difficulty in formatting for exporting notes as PDF
Settled for exporting markdown text as .txt files

Cleanup unneeded methods inside notesEditor.js since we are now using an SPA

### CODE REVIEW

**Comment by MarcBaeuerle** [comment]
line 176 editor.js

We cant create event listeners like this because they will stack on top of each other when switching to different notes. these event listeners work on the previous project because they reinitialized the functions when switching notes/pages. I had to create new functions that were separate from the button and make the buttons call those functions. I added constants at the top of index.js that reference the note id and the database that can be called inside the function so you don't need to pass parameters. those two changes should be enough

**Comment by MarcBaeuerle** [comment]
💦💦💦💦💦💦💦💦💦💦

**Review by MarcBaeuerle — APPROVED** [review]
lgtm

**Comment by kNelakonda** [comment]
looks good

**Pull request merged**
